services:
  etcd:
    image: "quay.io/coreos/etcd:v3.6.7"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"] # The health check command
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
